<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EquipmentCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('equipment_codes')->delete();

        $equipmentCodes = [
            ['code' => '100', 'description' => 'TABLES :', 'category_id' => 1],
            ['code' => '101', 'description' => 'Executive', 'category_id' => 1],
            ['code' => '102', 'description' => 'Clerical / Office', 'category_id' => 1],
            ['code' => '103', 'description' => 'Typing / Elementary', 'category_id' => 1],
            ['code' => '104', 'description' => 'Long / Rectangular', 'category_id' => 1],
            ['code' => '105', 'description' => 'Round, Square ( monobloc/wooden)', 'category_id' => 1],
            ['code' => '106', 'description' => 'Demonstration', 'category_id' => 1],
            ['code' => '107', 'description' => 'Laboratory', 'category_id' => 1],
            ['code' => '108', 'description' => 'Conference', 'category_id' => 1],
            ['code' => '109', 'description' => 'Lecture', 'category_id' => 1],
            ['code' => '110', 'description' => 'Drafting', 'category_id' => 1],
            ['code' => '111', 'description' => 'ALtar', 'category_id' => 1],
            ['code' => '112', 'description' => 'Faculty / Teacher', 'category_id' => 1],
            ['code' => '113', 'description' => 'Computer', 'category_id' => 1],
            ['code' => '114', 'description' => 'Study / Reading', 'category_id' => 1],
            ['code' => '115', 'description' => 'Carrel', 'category_id' => 1],
            ['code' => '116', 'description' => 'Center / Side / Vanity', 'category_id' => 1],
            ['code' => '117', 'description' => 'Plinths, Tilt ( platform)', 'category_id' => 1],
            ['code' => '118', 'description' => 'Counter', 'category_id' => 1],
            ['code' => '119', 'description' => 'Cadaver', 'category_id' => 1],
            ['code' => '120', 'description' => 'Dining', 'category_id' => 1],
            ['code' => '121', 'description' => 'Prep (stainless/steel)', 'category_id' => 1],
            ['code' => '122', 'description' => 'Over bed / bed', 'category_id' => 1],
            ['code' => '123', 'description' => 'Traction', 'category_id' => 1],
            ['code' => '124', 'description' => 'Architectural / Drawing', 'category_id' => 1],
            ['code' => '200', 'description' => 'CHAIRS:', 'category_id' => 2],
            ['code' => '201', 'description' => 'Executive', 'category_id' => 2],
            ['code' => '202', 'description' => 'Swivel / conference', 'category_id' => 2],
            ['code' => '203', 'description' => 'Rabami', 'category_id' => 2],
            ['code' => '204', 'description' => 'Gang / bench', 'category_id' => 2],
            ['code' => '205', 'description' => 'Monobloc / Jasmine', 'category_id' => 2],
            ['code' => '206', 'description' => 'Visitor / stackable', 'category_id' => 2],
            ['code' => '207', 'description' => 'Sala / sofa / dining', 'category_id' => 2],
            ['code' => '208', 'description' => 'Wooden armchair', 'category_id' => 2],
            ['code' => '209', 'description' => 'Metal armchair', 'category_id' => 2],
            ['code' => '210', 'description' => 'Fiber glass', 'category_id' => 2],
            ['code' => '211', 'description' => 'Elementary', 'category_id' => 2],
            ['code' => '212', 'description' => 'Dental', 'category_id' => 2],
            ['code' => '213', 'description' => 'Wooden stool', 'category_id' => 2],
            ['code' => '214', 'description' => 'Monobloc stool', 'category_id' => 2],
            ['code' => '215', 'description' => 'ROund', 'category_id' => 2],
            ['code' => '216', 'description' => 'Chapel', 'category_id' => 2],
            ['code' => '217', 'description' => 'Wheel', 'category_id' => 2],
            ['code' => '218', 'description' => 'Barstool', 'category_id' => 2],
            ['code' => '219', 'description' => 'Rattan', 'category_id' => 2],
            ['code' => '220', 'description' => 'Furniture green upholstery', 'category_id' => 2],
            ['code' => '221', 'description' => 'Commode', 'category_id' => 2],
            ['code' => '222', 'description' => 'Cleopatra', 'category_id' => 2],
            ['code' => '223', 'description' => 'Plastic', 'category_id' => 2],
            ['code' => '224', 'description' => 'Phleb chair', 'category_id' => 2],
            ['code' => '225', 'description' => 'Bench metal frame', 'category_id' => 2],
            ['code' => '226', 'description' => 'High leg chair', 'category_id' => 2],
            ['code' => '300', 'description' => 'CABINETS / BOOKSHELVES', 'category_id' => 3],
            ['code' => '301', 'description' => 'Steel filing', 'category_id' => 3],
            ['code' => '302', 'description' => 'Wooden filing cabinet', 'category_id' => 3],
            ['code' => '303', 'description' => 'Wooden shelves/ bookshelves/ detachable', 'category_id' => 3],
            ['code' => '304', 'description' => 'Wooden / Medicine / modified / Built-in', 'category_id' => 3],
            ['code' => '305', 'description' => 'Libarary shelves / rack', 'category_id' => 3],
            ['code' => '306', 'description' => 'Display', 'category_id' => 3],
            ['code' => '307', 'description' => 'Steel Locker', 'category_id' => 3],
            ['code' => '308', 'description' => 'Wooden locker', 'category_id' => 3],
            ['code' => '309', 'description' => 'TV stand', 'category_id' => 3],
            ['code' => '310', 'description' => 'Stainless / shelves / proffer', 'category_id' => 3],
            ['code' => '311', 'description' => 'Planters box', 'category_id' => 3],
            ['code' => '312', 'description' => 'Palo china', 'category_id' => 3],
            ['code' => '313', 'description' => 'OHP cabinet / side drawer', 'category_id' => 3],
            ['code' => '314', 'description' => 'Bullet recovery box', 'category_id' => 3],
            ['code' => '315', 'description' => 'Rostrum', 'category_id' => 3],
            ['code' => '316', 'description' => 'Bookstand', 'category_id' => 3],
            ['code' => '317', 'description' => 'Wooden booktruck', 'category_id' => 3],
            ['code' => '318', 'description' => 'Metal frame booktruck', 'category_id' => 3],
            ['code' => '319', 'description' => 'Depository cabinet', 'category_id' => 3],
            ['code' => '400', 'description' => 'EQUIPMENT', 'category_id' => 4],
            ['code' => '401', 'description' => 'Computer monitor', 'category_id' => 4],
            ['code' => '402', 'description' => 'CPU', 'category_id' => 4],
            ['code' => '403', 'description' => 'LCD projector', 'category_id' => 4],
            ['code' => '404', 'description' => 'Xerox Machine', 'category_id' => 4],
            ['code' => '405', 'description' => 'Fax Machine', 'category_id' => 4],
            ['code' => '406', 'description' => 'Aircondition / air curtain / air cooler', 'category_id' => 4],
            ['code' => '407', 'description' => 'Amplifier / Dual channel / video matrix', 'category_id' => 4],
            ['code' => '408', 'description' => 'Mixer / tape deck / equalizer / cctv', 'category_id' => 4],
            ['code' => '409', 'description' => 'Speaker / Headset / Headphone', 'category_id' => 4],
            ['code' => '410', 'description' => 'CD / DVD Player', 'category_id' => 4],
            ['code' => '411', 'description' => 'TV / LED TV', 'category_id' => 4],
            ['code' => '412', 'description' => 'Karaoke / Car Stereo / Tuner', 'category_id' => 4],
            ['code' => '413', 'description' => 'Cassette Player / Recorder', 'category_id' => 4],
            ['code' => '414', 'description' => 'VHS Player', 'category_id' => 4],
            ['code' => '415', 'description' => 'Telephone / Cellphone / TAB', 'category_id' => 4],
            ['code' => '416', 'description' => 'OHP', 'category_id' => 4],
            ['code' => '417', 'description' => 'Generator', 'category_id' => 4],
            ['code' => '418', 'description' => 'Fitness equipment / body building', 'category_id' => 4],
            ['code' => '419', 'description' => 'WHite screen / tripod / monopod', 'category_id' => 4],
            ['code' => '420', 'description' => 'Organ / Piano / Musical Instrument/ keyboard', 'category_id' => 4],
            ['code' => '421', 'description' => 'Industrial / coolmate', 'category_id' => 4],
            ['code' => '422', 'description' => 'Electric / wall/ ceiling/ rotary fan/ orbit/ exhaust', 'category_id' => 4],
            ['code' => '423', 'description' => 'Microphone / Lapel/ Stand', 'category_id' => 4],
            ['code' => '424', 'description' => 'Printer', 'category_id' => 4],
            ['code' => '425', 'description' => 'Laptop / tab', 'category_id' => 4],
            ['code' => '426', 'description' => 'Microscope', 'category_id' => 4],
            ['code' => '427', 'description' => 'Stethoscope', 'category_id' => 4],
            ['code' => '428', 'description' => 'Laboratory equipment', 'category_id' => 4],
            ['code' => '429', 'description' => 'Riffle / Gun', 'category_id' => 4],
            ['code' => '430', 'description' => 'Typewriter / Binding Machine', 'category_id' => 4],
            ['code' => '431', 'description' => 'Mimeo Machine / Risograph / Paper cutter', 'category_id' => 4],
            ['code' => '432', 'description' => 'Refrigerator / freezer / chiller', 'category_id' => 4],
            ['code' => '433', 'description' => 'Gas stove / gas range / electric/kettle', 'category_id' => 4],
            ['code' => '434', 'description' => 'Microwave oven / oven toaster / deck', 'category_id' => 4],
            ['code' => '435', 'description' => 'Shredding Machine', 'category_id' => 4],
            ['code' => '436', 'description' => 'Scanner', 'category_id' => 4],
            ['code' => '437', 'description' => 'Camera/ Digital / Video', 'category_id' => 4],
            ['code' => '438', 'description' => 'Musical instument', 'category_id' => 4],
            ['code' => '439', 'description' => 'Washing machine', 'category_id' => 4],
            ['code' => '440', 'description' => 'Weighing scale', 'category_id' => 4],
            ['code' => '441', 'description' => 'Dental instrument', 'category_id' => 4],
            ['code' => '442', 'description' => 'Engineering instrument / equipment', 'category_id' => 4],
            ['code' => '443', 'description' => 'Nursing instument / equipment', 'category_id' => 4],
            ['code' => '444', 'description' => 'Cash register / Calculator/ Adding Machine', 'category_id' => 4],
            ['code' => '445', 'description' => 'AVR / UPS / Regulator', 'category_id' => 4],
            ['code' => '446', 'description' => 'Fire extinguisher', 'category_id' => 4],
            ['code' => '447', 'description' => 'Beds', 'category_id' => 4],
            ['code' => '448', 'description' => 'Transformer', 'category_id' => 4],
            ['code' => '449', 'description' => 'Barcode scanner', 'category_id' => 4],
            ['code' => '450', 'description' => 'Thermal printer', 'category_id' => 4],
            ['code' => '451', 'description' => 'Rice cooker / induction cooker', 'category_id' => 4],
            ['code' => '452', 'description' => 'Stainless burner', 'category_id' => 4],
            ['code' => '453', 'description' => 'Stainless sink', 'category_id' => 4],
            ['code' => '454', 'description' => 'Blender', 'category_id' => 4],
            ['code' => '455', 'description' => 'Griller / Griddle', 'category_id' => 4],
            ['code' => '456', 'description' => 'Money detector / money counter', 'category_id' => 4],
            ['code' => '457', 'description' => 'Vault machine', 'category_id' => 4],
            ['code' => '458', 'description' => 'Component / Sound system', 'category_id' => 4],
            ['code' => '459', 'description' => 'Fryer', 'category_id' => 4],
            ['code' => '460', 'description' => 'Broiler', 'category_id' => 4],
            ['code' => '461', 'description' => 'Mixer / Juicer', 'category_id' => 4],
            ['code' => '462', 'description' => 'Meat grinder / slicer', 'category_id' => 4],
            ['code' => '463', 'description' => 'Dish washer stainless / greas trap', 'category_id' => 4],
            ['code' => '464', 'description' => 'Rack stainless', 'category_id' => 4],
            ['code' => '465', 'description' => 'Canopy hood', 'category_id' => 4],
            ['code' => '466', 'description' => 'Charger', 'category_id' => 4],
            ['code' => '467', 'description' => 'Crim laboratory', 'category_id' => 4],
            ['code' => '468', 'description' => 'Sewing Machine', 'category_id' => 4],
            ['code' => '469', 'description' => 'OT equipment', 'category_id' => 4],
            ['code' => '470', 'description' => 'Heater / Hand dryer', 'category_id' => 4],
            ['code' => '471', 'description' => 'Water Dispenser', 'category_id' => 4],
            ['code' => '472', 'description' => 'Hard drive', 'category_id' => 4],
            ['code' => '473', 'description' => 'Wifi / router/ d-link', 'category_id' => 4],
            ['code' => '474', 'description' => 'Polisher', 'category_id' => 4],
        ];

        foreach ($equipmentCodes as &$row) {
            $row['created_at'] = $now;
            $row['updated_at'] = $now;
        }

        DB::table('equipment_codes')->insert($equipmentCodes);
    }
}
